# Generated by Django 6.1.1 on 2026-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
